/*
 * Simple API
 *
 * A simple API to learn how to write OpenAPI Specification
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"fmt"
	"net/http"
	"strings"
	"github.com/gorilla/mux"
	"github.com/jinzhu/gorm"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

var db *gorm.DB

func NewRouter(pdb * gorm.DB) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	db = pdb
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/openapi101/",
		Index,
	},

	Route{
		"PersonsGet",
		strings.ToUpper("Get"),
		"/openapi101/persons",
		PersonsGet,
	},

	Route{
		"PersonsPost",
		strings.ToUpper("Post"),
		"/openapi101/persons",
		PersonsPost,
	},

	Route{
		"PersonsUsernameDelete",
		strings.ToUpper("Delete"),
		"/openapi101/persons/{username}",
		PersonsUsernameDelete,
	},

	Route{
		"PersonsUsernameFriendsGet",
		strings.ToUpper("Get"),
		"/openapi101/persons/{username}/friends",
		PersonsUsernameFriendsGet,
	},

	Route{
		"PersonsUsernameGet",
		strings.ToUpper("Get"),
		"/openapi101/persons/{username}",
		PersonsUsernameGet,
	},
}
